/*
 * This source file was generated by the Gradle 'init' task
 */
package com.vodden.aoc

import org.junit.jupiter.api.Test
import org.junit.jupiter.api.Assertions.assertEquals

class Day04Test {
    @Test
    fun testPartOne() {
        assertEquals(13, Day04().part1())
        assertEquals(0, Day04().part2())
    }
}
