/*
 * This source file was generated by the Gradle 'init' task
 */
package com.vodden.aoc

import org.junit.jupiter.api.Test
import org.junit.jupiter.api.Assertions.assertEquals

class Day03Test {
    @Test
    fun testPartOne() {
        assertEquals(357, Day03().part1())
        assertEquals(3121910778619, Day03().part2())
    }
}
