/*
 * This source file was generated by the Gradle 'init' task
 */
package com.vodden.aoc

import org.junit.jupiter.api.Test
import org.junit.jupiter.api.Assertions.assertEquals

class Day05Test {
    @Test
    fun testPartOne() {
        assertEquals(3, Day05().part1())
        assertEquals(14, Day05().part2())
    }
}
