/*
 * This source file was generated by the Gradle 'init' task
 */
package com.vodden.aoc

import org.junit.jupiter.api.Test
import org.junit.jupiter.api.Assertions.assertEquals

class Day02Test {
    @Test
    fun testPartOne() {
        val classUnderTest = Day02()
        assertEquals(1227775554, Day02().part1())
    }
}
