/*
 * This source file was generated by the Gradle 'init' task
 */
package com.vodden.aoc

public fun <T> zip(vararg lists: List<T>): List<List<T>> {
    return zip(*lists, transform = { it })
}

public inline fun <T, V> zip(vararg lists: List<T>, transform: (List<T>) -> V): List<V> {
    val minSize = lists.map(List<T>::size).min() 
    val list = ArrayList<V>(minSize)

    val iterators = lists.map { it.iterator() }
    var i = 0
    while (i < minSize) {
        list.add(transform(iterators.map { it.next() }))
        i++
    }

    return list
}

class Day06 {
    val input = requireNotNull(object {}.javaClass.getResource("/input.txt")
        ?.readText(), {"Failed to read input file"})

    fun part1(): Long = 
        zip(
            *input.lines()
            .map { it.split(" ").filter { it.isNotEmpty() } }
            .toTypedArray()
        )
        .map { l -> when(l.last()) {
            "+" -> l.take(l.size - 1).fold(0L) { acc, next -> (acc + next.toLong()) }
            "*" -> l.take(l.size - 1).fold(1L) { acc, next -> (acc * next.toLong()) }
            else -> 0L
        } }.sum()

    fun part2(): Long {
        val lines = input.lines()
        val numbers = zip(*lines
            .dropLast(1)
            .map { it.toList() }
            .toTypedArray())
            .map { it.joinToString("") }
            .fold(listOf(listOf<String>())) { acc, col ->
                if (col.isBlank()) {
                    if (acc.last().isNotEmpty()) acc + listOf(emptyList())
                    else acc
                } else {
                    acc.dropLast(1) + listOf(acc.last() + col)
                }
            }
            .filter { it.isNotEmpty() }
            .map { it.map { s -> s.trim().toLong() } }

        val operators = lines.last()
            .toList().filter({ it != ' ' })

        return operators.zip(numbers).sumOf { (opp, list) ->
            when(opp) {
                '+' -> list.reduce { acc, itm -> acc + itm }
                '*' -> list.reduce { acc, itm -> acc * itm }
                else -> 0L
            }
        }
    }
}

fun main() {
    println(Day06().part1())
    println(Day06().part2())
}