/*
 * This source file was generated by the Gradle 'init' task
 */
package com.vodden.aoc

import kotlin.requireNotNull

public fun <T> zip(vararg lists: List<T>): List<List<T>> {
    return zip(*lists, transform = { it })
}

public inline fun <T, V> zip(vararg lists: List<T>, transform: (List<T>) -> V): List<V> {
    val minSize = lists.map(List<T>::size).min() 
    val list = ArrayList<V>(minSize)

    val iterators = lists.map { it.iterator() }
    var i = 0
    while (i < minSize) {
        list.add(transform(iterators.map { it.next() }))
        i++
    }

    return list
}

class Day06 {
    fun part1() : Long {
        val input = object {}.javaClass.getResource("/input.txt")
            ?.readText()
        requireNotNull(input) {"Failed to read input file"}
        
        return zip(
            *input.lines()
            .map { it.split(" ").filter( { it.isNotEmpty() }) }
            .toTypedArray()
        )
        .map { l -> when(l.last()) {
            "+" -> l.take(l.size - 1).fold(0L) { acc, next -> (acc + next.toLong()) }
            "*" -> l.take(l.size - 1).fold(1L) { acc, next -> (acc * next.toLong()) }
            else -> 0L
        } }.sum()
    }
}

fun main() {
    print(Day06().part1())
}