/*
 * This source file was generated by the Gradle 'init' task
 */
package com.vodden.aoc

class Day07 {

    fun inputGetter(): List<String> {
        val input = this::class.java.getResource("/input.txt")
            ?.readText()?.lines()

        requireNotNull(input) {"Failed to read input file"}
        return input
    }

    private val input by lazy { inputGetter() }
    private val start by lazy { input[0].indexOf('S') }
    private val len by lazy { input[0].length }


    fun part1() : Int {
        val tachyonPositions = mutableSetOf<Int>()
        tachyonPositions.add(start)

        var splits = 0
        input.drop(1).forEach { line ->
            line.withIndex()
                .filter { (_, c) -> c == '^' }
                .filter { (idx, _) -> idx in tachyonPositions }
                .forEach { (idx, _) ->
                    if (idx > 0) tachyonPositions.add(idx - 1)
                    if (idx < len - 1) tachyonPositions.add(idx + 1)
                    tachyonPositions.remove(idx)
                    splits++
                }
        }

        return splits
    }
    
    fun part2() : Long {
        val paths = LongArray(len) { 0L }
        paths[start] = 1L

        input.drop(1).forEach { line ->
            line.withIndex()
                .filter { (_, c) -> c == '^' }
                .filter { (idx, _) -> paths[idx] > 0L }
                .forEach { (idx, _) ->
                    if (idx > 0) paths[idx - 1] += paths[idx]
                    if (idx < len - 1) paths[idx + 1] += paths[idx]
                    paths[idx] = 0L
                }
        }

        return paths.sum()
    }
}

fun main() {
    println(Day07().part1())
    println(Day07().part2())
}