/*
 * This source file was generated by the Gradle 'init' task
 */
package com.vodden.aoc

import kotlin.math.sqrt
import kotlin.requireNotNull

class Day08 {

    private val input by lazy { 
        val input = this::class.java.getResource("/input.txt")
            ?.readText()?.lines()

        requireNotNull(input) {"Failed to read input file"}
        input
    }

    private val junctionBoxes by lazy {
        input.map {  it.split(",").map { it.toLong() } }
    }


    fun part1(connections: Int = 1000) : Int {
        val sortedPairs = junctionBoxes.flatMap { lhs -> junctionBoxes.map { rhs -> Pair(lhs, rhs) } }
            .filter { (a, b) -> a != b }
            .sortedBy { (a, b) -> 
                val dx = a[0] - b[0]
                val dy = a[1] - b[1]
                val dz = a[2] - b[2]
                - (dx * dx + dy * dy + dz * dz)
            }

        val circuits = hashMapOf<List<Long>, Set<List<Long>>>(*junctionBoxes.map { p -> p to setOf(p) }.toTypedArray())
        
        sortedPairs.take(connections).forEach { (a, b) ->
            val (circuit1, jBoxes1) = circuits.entries.first { (_, jBoxes) ->
                a in jBoxes
            }
            val (circuit2, jBoxes2) = circuits.entries.first { (_, jBoxes) ->
                b in jBoxes
            }
            if (circuit1 != circuit2) {
                circuits[a] = jBoxes1 + jBoxes2
                circuits.remove(b)
            }
            println(circuits)
        }

        println(
            circuits.values
            .map { it.size }
            .sortedDescending()
        )

        val circuitSizes = circuits.values
            .map { it.size }
            .sortedDescending()
            .take(3)
            .fold(1) { acc, v -> acc * v }

        return circuitSizes
    }
    
    fun part2() : Long {
        return 0L
    }
}

fun main() {
    println(Day08().part1())
    println(Day08().part2())
}