/*
 * This source file was generated by the Gradle 'init' task
 */
package com.vodden.aoc

class Day08 {

    private data class Point3D(val x: Long, val y: Long, val z: Long)

    private val input: List<String> by lazy {
        requireNotNull(this::class.java.getResource("/input.txt")
            .readText().lines().filter{ it.isNotBlank() }, {
            "Failed to read input file"
        })
    }

    private val junctionBoxes by lazy {
        input.map { line -> 
            val (x, y, z) = line.split(",").map { it.toLong() }
            Point3D(x, y, z)
        }
    }

    private fun distanceSquared(a: Point3D, b: Point3D): Long {
        val dx = a.x - b.x
        val dy = a.y - b.y
        val dz = a.z - b.z
        return dx * dx + dy * dy + dz * dz
    }

    private val sortedPairs by lazy {
        junctionBoxes.indices.flatMap { i ->
            (i + 1 until junctionBoxes.size).map { j ->
                i to j
            }
        }.sortedBy { (i, j) -> distanceSquared(junctionBoxes[i], junctionBoxes[j]) }
    }

    private class UnionFind(size: Int) {
        private val parent = IntArray(size) { it }
        private val componentSize = IntArray(size) { 1 }

        fun find(index: Int): Int {
            if (parent[index] != index) {
                parent[index] = find(parent[index]) // path compression
            }
            return parent[index]
        }

        fun union(a: Int, b: Int): Boolean {
            val rootA = find(a)
            val rootB = find(b)

            if (rootA == rootB) return false

            // Union by size: attach smaller tree to larger tree
            if (componentSize[rootA] < componentSize[rootB]) {
                parent[rootA] = rootB
                componentSize[rootB] += componentSize[rootA]
            } else {
                parent[rootB] = rootA
                componentSize[rootA] += componentSize[rootB]
            }
            return true
        }

        val componentSizes: List<Int>
            get() = parent.indices
                .filter { parent[it] == it }
                .map { componentSize[it] }

        val componentCount: Int
            get() = parent.indices.count { parent[it] == it }
    }

    fun part1(connections: Int = 1000): Int {
        val uf = UnionFind(junctionBoxes.size)

        sortedPairs.take(connections).forEach { (i, j) ->
            uf.union(i, j)
        }

        return uf.componentSizes
            .sortedDescending()
            .take(3)
            .fold(1, Int::times)
    }

    fun part2(): Long {
        val uf = UnionFind(junctionBoxes.size)
        var components = junctionBoxes.size

        val result = sortedPairs.first { (i, j) ->
            if(uf.union(i, j)) components--
            components == 1
        }

        return junctionBoxes[result.first].x * junctionBoxes[result.second].x
    }
}

fun main() {
    println(Day08().part1())
    println(Day08().part2())
}