/*
 * This source file was generated by the Gradle 'init' task
 */
package com.vodden.aoc

import org.junit.jupiter.api.Test
import org.junit.jupiter.api.Assertions.assertEquals


class AppTest {
    @Test fun exampleGivesCorrectValue() {
        val lines = object {}.javaClass.getResourceAsStream("/test.txt")?.bufferedReader()?.readLines()
        
        assertEquals(3, App().process(lines!!))
    }

    @Test fun p2ExampleGivesCorrectValue() {
        val lines = object {}.javaClass.getResourceAsStream("/test.txt")?.bufferedReader()?.readLines()
        
        assertEquals(6, App().processP2(lines!!))
    }
}
