/*
 * This source file was generated by the Gradle 'init' task
 */
package com.vodden.aoc

import org.junit.jupiter.api.Test
import org.junit.jupiter.api.Assertions.assertEquals

class Day06Test {
    @Test
    fun testPartOne() {
        assertEquals(4277556, Day06().part1())
    }
}
