/*
 * This source file was generated by the Gradle 'init' task
 */
package com.vodden.aoc25.day01

class App {
    fun process(lines: List<String>): Int {
        var accumulator = 50
        var numOfZeros = 0
        for (line in lines.iterator()) {
            val value = line.substring(1).toInt()

            when(line[0]) {
                'L' -> accumulator -= value
                'R' -> accumulator += value
            }

            if (accumulator.mod(100) == 0) {
                numOfZeros++
            }
        }

        return numOfZeros
    }

    fun processP2(lines: List<String>): Int {
        var accumulator = 50
        var numOfZeroCrossings = 0
        for (line in lines.iterator()) {
            val value = line.substring(1).toInt()

            when(line[0]) {
                'R' ->  {
                    numOfZeroCrossings += (accumulator + value) / 100
                    accumulator = (accumulator + value).mod(100)
                }
                'L' -> {
                    val flippedAccumulator = (100-accumulator).mod(100)
                    numOfZeroCrossings += (flippedAccumulator + value) / 100
                    accumulator = (accumulator - value).mod(100)

                }
            }
        }

        return numOfZeroCrossings
    }
}

fun main() {
    val lines = object {}.javaClass.getResourceAsStream("/input.txt")?.bufferedReader()?.readLines()
    println(App().process(lines!!))
    println(App().processP2(lines!!))
}
