/*
 * This source file was generated by the Gradle 'init' task
 */
package com.vodden.aoc

import kotlin.requireNotNull
import kotlin.require


class Day04 {
    val input : String by lazy { 
            val input = object {}.javaClass.getResource("/input.txt")?.readText()
            requireNotNull(input) { "Could not open input.txt resource." }
            input
        }

    val rollsOfPaper : List<Pair<Int, Int>> by lazy {
        val rollsOfPaper = mutableListOf<Pair<Int, Int>>()

        input.lines().withIndex().forEach { (y, line) -> 
            line.withIndex().forEach { (x, c) -> 
                if (c == '@') rollsOfPaper.add(Pair(x, y))
            }
        }

        rollsOfPaper
    }
    
    fun adjacent(x: Int, y: Int) = listOf(
        Pair(x-1, y-1),
        Pair(x-1, y),
        Pair(x-1, y+1),
        Pair(x, y-1),
        Pair(x, y+1),
        Pair(x+1, y-1),
        Pair(x+1, y),
        Pair(x+1, y+1),
    )

    fun part1() : Int {
        return rollsOfPaper.filter { (x, y) -> 
            adjacent(x, y).filter { rollsOfPaper.contains(it) }.size < 4
        }.size
    }


    fun part2(): Int {
        return 0
    }

}

fun main() {
    println(Day04().part1())
    println(Day04().part2())
}