/*
 * This source file was generated by the Gradle 'init' task
 */
package com.vodden.aoc

import kotlin.requireNotNull

class Day04 {
    val input: String by lazy { 
        requireNotNull(object {}.javaClass.getResource("/input.txt")?.readText(),
            { "Could not open input.txt resource." })
    }

    val rollsOfPaper: Set<Pair<Int, Int>> by lazy {
        input.lines().flatMapIndexed { y, line -> 
            line.withIndex().mapNotNull { (x, c) ->
                if (c == '@') x to y else null
            }
        }.toSet()
    }

    private val adjacentOffsets = listOf(
       -1 to -1, -1 to 0, -1 to 1,
        0 to -1,           0 to 1,
        1 to -1,  1 to 0,  1 to 1
    )
    
    fun adjacent(x: Int, y: Int) = 
        adjacentOffsets.map { (dx, dy) -> (x + dx) to (y + dy) }

    fun part1() : Int {
        return rollsOfPaper.count { (x, y) -> 
            adjacent(x, y).count { it in rollsOfPaper } < 4
        }
    }

    fun part2(): Int {
        return generateSequence(rollsOfPaper) { current ->
            current.firstOrNull { (x, y) ->
                adjacent(x, y).count { it in current } < 4
            }?.let { current - it }
        }.count() - 1
    }

}

fun main() {
    println(Day04().part1())
    println(Day04().part2())
}