/*
 * This source file was generated by the Gradle 'init' task
 */
package com.vodden.aoc

import org.junit.jupiter.api.Test
import org.junit.jupiter.api.Assertions.assertEquals

import java.math.BigInteger

class Day08Test {
    @Test
    fun testPartOne() {
        assertEquals(40, Day08().part1(10))
        assertEquals(0L, Day08().part2())
    }
}
