/*
 * This source file was generated by the Gradle 'init' task
 */
package com.vodden.aoc

class Day02 {
    private val input by lazy {
        requireNotNull(object {}.javaClass.getResource("/input.txt")?.readText())
    }

    private val ranges by lazy {
        input
            .trim()
            .split(',')
            .map { it.substringBefore('-').trim().toLong()..it.substringAfter('-').trim().toLong() }
    }

    fun part1() : Long? {
        val regex = """(.*)\1""".toRegex()
        return ranges.map {     
            it.filter { regex.matches(it.toString()) }.sum()
        }.sum()
    }
    
    fun part2() : Long? {
        val regex = """(.*)\1+""".toRegex()
        return ranges.map {     
            it.filter { regex.matches(it.toString()) }.sum()
        }.sum()
    }
}

fun main() {
    println(Day02().part1())
    println(Day02().part2())
}
