/*
 * This source file was generated by the Gradle 'init' task
 */
package com.vodden.aoc

import kotlin.requireNotNull

fun LongRange.canMerge(other:LongRange):Boolean =
    (this.first in other) || (this.last in other) ||
    (other.first in this) || (other.last in this)

fun LongRange.merge(other:LongRange):LongRange =
    minOf(this.first, other.first) .. maxOf(this.last, other.last)

// This is needed because the built-in count():Int doesn't take into
// account that a long range count could be greater than Int.max
fun LongRange.countLong():Long = last - first + 1L

// Traverses each element in the SORTED and merges elements
// that can be merged.
fun List<LongRange>.performMerge():List<LongRange> =
    this.drop(1)
        .fold(listOf<LongRange>() to this[0]) { (acc, last), it ->
            if (last.canMerge(it)) acc to last.merge(it)
            else (acc + listOf(last)) to it
        }.let{ it.first + listOf(it.second) }



class Day05 {
    val input : String
        get() = object {}.javaClass.getResource("/input.txt")?.readText()!!        

    fun part1() : Int {
        requireNotNull(input) {"Failed to read input file"}
        val (ranges, ids) = input.split("\n\n")
    
        val newRanges = ranges.lines()
            .map { it.split("-") }
            .map { it[0].toLong()..it[1].toLong() }

        
        return ids.lines()
            .filter {it != ""}
            .map { it.toLong() }
            .filter { id -> newRanges.any { id in it } }.size
    }


    fun part2():Long {
        requireNotNull(input) {"Failed to read input file"}
    
        val (ranges, _) = input.split("\n\n")
        val newRanges = ranges.lines()
            .map { it.split("-") }
            .map { it[0].toLong()..it[1].toLong() }

        return newRanges.sortedBy{it.first}.performMerge().sumOf{it.countLong()}
    }

}

fun main() {
    println(Day05().part1())
    println(Day05().part2())
}