/*
 * This source file was generated by the Gradle 'init' task
 */
package com.vodden.aoc

import org.junit.jupiter.api.Test
import org.junit.jupiter.api.Assertions.assertEquals

import java.math.BigInteger

class Day07Test {
    @Test
    fun testPartOne() {
        assertEquals(21, Day07().part1())
        assertEquals(40L, Day07().part2())
    }
}
