/*
 * This source file was generated by the Gradle 'init' task
 */
package com.vodden.aoc

class Day01 {
    fun process(lines: List<String>): Int {
        val (_, numOfZeros) = lines.fold(Pair(50, 0)) { (accumulator, numOfZeros), line ->
            val value = line.substring(1).toInt()
            val nextAcc = when(line[0]) {
                'L' -> accumulator - value
                'R' -> accumulator + value
                else -> accumulator
            }
            Pair(nextAcc, if (accumulator.mod(100) == 0) numOfZeros + 1 else numOfZeros)
        }
        return numOfZeros
    }

    fun processP2(lines: List<String>): Int {
        val (_, numOfZeroCrossings) = lines.fold(Pair(50, 0)) { (accumulator, numOfZeroCrossings), line ->
            val value = line.substring(1).toInt()
            val (newPos, addedCrossings) = when(line[0]) {
                'R' -> Pair( (accumulator + value).mod(100), (accumulator + value) / 100 )
                'L' -> {
                    val flippedAccumulator = (100-accumulator).mod(100)
                    Pair((accumulator - value).mod(100), (flippedAccumulator + value) / 100)
                }
                else -> Pair(accumulator, numOfZeroCrossings)
            }
            Pair(newPos, numOfZeroCrossings + addedCrossings)
        }
        return numOfZeroCrossings
    }
}

fun main() {
    val lines = object {}.javaClass.getResource("/input.txt")
        ?.readText()
        ?.lines()
        ?.filter { it.isNotBlank() }
    
    if(lines != null) {
        println(Day01().process(lines))
        println(Day01().processP2(lines))
    }
}
