/*
 * This source file was generated by the Gradle 'init' task
 */
package com.vodden.aoc

class Day03 {
    val input: String by lazy { 
        requireNotNull(object {}.javaClass.getResource("/input.txt")?.readText(),
            { "Could not open input.txt resource." })
    }

    val banks by lazy { 
        input.lines().map { line -> line.map(Char::digitToInt) }
    }

    fun maxNumber(bank: List<Int>, digits: Int): Long {
        return (digits downTo 1).fold(0L to 0) { (value, start), remaining ->
            val (max, maxPos) = (start..bank.size - remaining)
                .map { bank[it] to it }
                .maxBy { it.first }
            (value * 10 + max) to (maxPos + 1)
        }.first
    }

    fun part1() = banks.sumOf { maxNumber(it, 2)  }
    fun part2() = banks.sumOf { maxNumber(it, 12) }
}

fun main() {
    println(Day03().part1())
    println(Day03().part2())
}