/*
 * This source file was generated by the Gradle 'init' task
 */
package com.vodden.aoc

import kotlin.requireNotNull

class Day03 {
    val input: String by lazy { 
        requireNotNull(object {}.javaClass.getResource("/input.txt")?.readText(),
            { "Could not open input.txt resource." })
    }

    val banks by lazy { 
        input.lines().map { line -> line.map(Char::digitToInt) }
    }
    
    fun part1() : Int {
        return banks.map { 
            bank -> bank
                .withIndex()
                .flatMap { (idx, bat) -> bank.drop(idx + 1).map { bat to it} }
                .map { (10*it.first) + it.second }
                .max()
        }.sum()
    }

    fun part2(): Int {
        return 0
    }

}

fun main() {
    println(Day03().part1())
    println(Day03().part2())
}