/*
 * This source file was generated by the Gradle 'init' task
 */
package com.vodden.aoc

import org.junit.jupiter.api.Test
import org.junit.jupiter.api.Assertions.assertEquals

import java.math.BigInteger

class Day09Test {
    @Test
    fun testPartOne() {
        assertEquals(50, Day09().part1())
        assertEquals(0, Day09().part2())
    }
}
