/*
 * This source file was generated by the Gradle 'init' task
 */
package com.vodden.aoc

import kotlin.math.abs

data class Point(val x: Long, val y: Long)
data class Rectangle(val p1: Point, val p2: Point) {
    val minX = minOf(p1.x, p2.x)
    val maxX = maxOf(p1.x, p2.x)
    val minY = minOf(p1.y, p2.y)
    val maxY = maxOf(p1.y, p2.y)

    val area: Long by lazy { (abs(p1.x - p2.x) + 1) * (abs(p1.y - p2.y) + 1) }

    fun intersects(other: Rectangle): Boolean {
        return minX < other.maxX && maxX > other.minX &&
               minY < other.maxY && maxY > other.minY
    }
}
typealias Line = Rectangle

class Day09 {
    private val redTiles: List<Point> by lazy {
        this::class.java.getResource("/input.txt")
            ?.readText()
            ?.trim()
            ?.lines()
            ?.filter{ it.isNotBlank() }
            ?.map { line ->
                val (x, y) = line.split(",").map { it.toLong() }
                Point(x, y)
            }
            ?: error("Input not found!")
    }

    private val lines: List<Line> by lazy { 
        (redTiles + redTiles.first()).windowed(2).map( { Rectangle(it.first(), it.last()) } )
    }
    
    private fun rectangles(): Sequence<Rectangle> = sequence {
        redTiles.withIndex().forEach { (idx, t1) ->
            redTiles.drop(idx + 1).forEach { t2 ->
                yield(Rectangle(t1, t2))
            }
        }
    }

    fun part1(): Long = rectangles().maxOf {it.area}

    fun part2(): Long {
        return rectangles()
            .sortedByDescending { it.area }
            .first { rectangle -> lines.none { it.intersects(rectangle) } }
            .area
    }
}

fun main() {
    println(Day09().part1())
    println(Day09().part2())
}