/*
 * This source file was generated by the Gradle 'init' task
 */
package com.vodden.aoc

import kotlin.math.abs

typealias Tile = Pair<Long, Long>

class Day09 {
    private val input: List<String> by lazy {
        requireNotNull(this::class.java.getResource("/input.txt")
            .readText().lines().filter{ it.isNotBlank() }, {
            "Failed to read input file"
        })
    }

    private val redTiles: List<Tile> by lazy {
        input.map { it.split(",") }
            .map { it[0].toLong() to it[1].toLong() }
    }
    
    private val pairs: List<Pair<Tile,Tile>> by lazy {
        redTiles.withIndex().flatMap { (idx, t1) ->
            redTiles.drop(idx + 1).map { t2 ->
                t1 to t2
            }
        }
    }

    fun area(lhs: Tile, rhs: Tile): Long =
        (abs(lhs.first - rhs.first) + 1) *
        (abs(lhs.second - rhs.second) + 1)

    fun part1(): Long = pairs.map({ area(it.first, it.second) }).sorted().last()

    fun part2(): Long = 0L
}

fun main() {
    println(Day09().part1())
    println(Day09().part2())
}