/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example

import org.junit.jupiter.api.Test
import org.junit.jupiter.api.Assertions.assertEquals

class AppTest {
    @Test
    fun testPartOne() {
        val classUnderTest = App()
        assertEquals(1227775554, App().part1())
    }
}
