/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example

class App {
    fun part1() : List<Pair<String,String>>? {
        val input = object {}.javaClass.getResource("/input.txt")
            ?.readText()
            ?.trim()
            ?.split(',')
            ?.map { Pair(  it.substringBefore('-').trim(), it.substringAfter('-').trim()) }
        return input
    }
}

fun main() {
    print(App().part1())
}
